"""empty message

Revision ID: 4d66bdc246b6
Revises: e915c1aa7256
Create Date: 2020-11-02 17:08:15.672505

"""

# revision identifiers, used by Alembic.
revision = '4d66bdc246b6'
down_revision = 'e915c1aa7256'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inspection_confirmations', ['id'])
    op.create_unique_constraint(None, 'inspection_times', ['id'])
    op.create_unique_constraint(None, 'inspections', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'inspections', type_='unique')
    op.drop_constraint(None, 'inspection_times', type_='unique')
    op.drop_constraint(None, 'inspection_confirmations', type_='unique')
    # ### end Alembic commands ###
