"""empty message

Revision ID: 749c42678b70
Revises: 8b5824a2d305
Create Date: 2021-01-29 11:30:39.805191

"""

# revision identifiers, used by Alembic.
revision = '749c42678b70'
down_revision = '8b5824a2d305'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_times', 'is_repeated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('inspections', sa.Column('flat_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'flat_count')
    op.alter_column('inspection_times', 'is_repeated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
