"""empty message

Revision ID: 8b5824a2d305
Revises: bb73e5f0ba9f
Create Date: 2020-12-15 18:24:02.152360

"""

# revision identifiers, used by Alembic.
revision = '8b5824a2d305'
down_revision = 'bb73e5f0ba9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_times', sa.Column('apartment_notes', sa.String(length=300), nullable=True))
    op.add_column('inspection_times', sa.Column('is_repeated', sa.Boolean(), nullable=False))
    op.add_column('inspections', sa.Column('employee', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'employee')
    op.drop_column('inspection_times', 'is_repeated')
    op.drop_column('inspection_times', 'apartment_notes')
    # ### end Alembic commands ###
