"""empty message

Revision ID: bb73e5f0ba9f
Revises: e915c1aa7256
Create Date: 2020-11-06 17:26:43.476748

"""

# revision identifiers, used by Alembic.
revision = 'bb73e5f0ba9f'
down_revision = 'e915c1aa7256'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inspection_confirmations', ['id'])
    op.create_unique_constraint(None, 'inspection_times', ['id'])
    op.create_unique_constraint(None, 'inspections', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'inspections', type_='unique')
    op.drop_constraint(None, 'inspection_times', type_='unique')
    op.drop_constraint(None, 'inspection_confirmations', type_='unique')
    # ### end Alembic commands ###
