"""empty message

Revision ID: e915c1aa7256
Revises: None
Create Date: 2020-11-01 11:16:32.960141

"""

# revision identifiers, used by Alembic.
revision = 'e915c1aa7256'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('street_number', sa.String(length=10), nullable=True),
    sa.Column('staircases', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inspection_confirmations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('inspection_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('additional_notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inspection_times',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('inspection_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_times')
    op.drop_table('inspection_confirmations')
    op.drop_table('users')
    op.drop_table('inspections')
    # ### end Alembic commands ###
